export const LANDSCAPE = {
  meta: {
    source: "feddit.dk platner search, pages 1-25, sort=New",
    subject: "Graham Platner - Maine Democratic Senate candidate vs. Susan Collins",
    note: "Qualitative discourse weights, not polls or vote share",
  },
  campSpectrum: {
    total: 100,
    segments: [
      { id: "pragmatic", value: 40, color: "green", label: "Pragmatic harm-reduction" },
      { id: "skeptical", value: 25, color: "yellow", label: "Skeptical conditional" },
      { id: "antiImp", value: 20, color: "pink", label: "Hard anti-imperialist" },
      { id: "boosters", value: 10, color: "blue", label: "Establishment-skeptic boosters" },
      { id: "anarchist", value: 5, color: "gray", label: "Anarchist / anti-electoral" },
    ],
  },
  camps: [
    {
      id: "pragmatic",
      name: "Pragmatic harm-reduction",
      swatchColor: "green",
      emphasis: 40,
      theory: "Win seats with populist messaging, shift the Overton window, prove the establishment wrong.",
      forPoints: [
        "Best instrument to beat Collins and shift policy on M4A, Gaza, wealth tax, anti-AIPAC",
        "Scandals framed as hit jobs from AIPAC, pro-Collins money, GOP, and establishment oppo",
        "Mamdani parallel: scandal-heavy populist who wins if economic message lands",
        "Town halls, labor language, and local campaign work cited as real policy competence",
        "Redemption arc plausible - Marine to oyster farmer to anti-oligarch candidate",
        "Bernie, AFL-CIO, Common Defense endorsements cited as legitimacy",
      ],
      againstPoints: ["Internal caveats only: still flawed, not a trusted movement leader"],
    },
    {
      id: "skeptical",
      name: "Skeptical conditional support",
      swatchColor: "yellow",
      emphasis: 25,
      theory: "Vote Collins out if no alternative; do not invest movement capital; Fetterman proved words do not equal votes.",
      forPoints: [
        "Collins is worse on every policy measure",
        "Electoral harm reduction is distinct from movement trust",
        "Political Pascal's wager: small downside risk vs. large upside vs. Mills/Collins",
      ],
      againstPoints: [
        "Fetterman comparison is central trauma - same aesthetic, staff echoes, will betray on Gaza",
        "No Mamdani-style pedigree: no DSA chapter, no vouching network",
        "Tattoo hinge: ignorance or lying both disqualifying for Senate power",
        "Do not organize for him - watch like a hawk if voting",
        "Smith-Rodriguez / Costello alternatives with less baggage were not mobilized",
        "Trust has to be earned over time through discipline, accountability, and votes",
      ],
    },
    {
      id: "antiImp",
      name: "Hard anti-imperialist rejection",
      swatchColor: "pink",
      emphasis: 20,
      theory: "Electoral politics absorbs left energy; sheepdog candidates discredit the movement; real change is unions and organizing outside Democrats.",
      forPoints: [],
      againstPoints: [
        "Nazi tattoo + war participation + contractor work = cannot be redeemed into Senate leadership",
        "Supporting him legitimizes empire regardless of Collins",
        "Fight Agency + Schumer endorsement = sheepdog / manufactured authenticity",
        "Efficient MIC under Platner worse than incompetent zombie",
        "No clear apology or reparative accounting to Iraqis and Afghans harmed by US wars",
        "If politician does not show empathy abroad, they may not care about you either",
      ],
    },
    {
      id: "boosters",
      name: "Establishment-skeptic boosters",
      swatchColor: "blue",
      emphasis: 10,
      theory: "DNC tried to stop him and failed - that proves he threatens the establishment.",
      forPoints: [
        "Schumer/DSCC backed Mills; dirty oppo ran; Mills dropped when polls collapsed",
        "AIPAC / pro-Collins / corporate-Dem attacks prove he is a real threat",
        "Populist who survived scandal wave while holding policy line",
      ],
      againstPoints: [
        "Skeptics cite Schumer eventually working with Platner as proof he is inside the tent",
        "Fight Agency overlap with Fetterman staff fuels co-option fears",
      ],
    },
    {
      id: "anarchist",
      name: "Anarchist / anti-electoral",
      swatchColor: "gray",
      emphasis: 5,
      theory: "Forgiveness not owed; engage elections only to expose parliamentarism's limits.",
      forPoints: [],
      againstPoints: [
        "Democrats are the enemy - harm-reduction voting still absorbs left energy",
        "Leadership inappropriate for war veterans with this record",
        "No Senate power for someone who needs reparative work, not a campaign",
      ],
    },
  ],
  instanceSplit: [
    { label: "lemmy.world / progressivepolitics", support: 70, reject: 30 },
    { label: "lemmy.ml / ML-aligned", support: 15, reject: 85 },
    { label: "Trans / identity-focused", support: 40, reject: 60 },
  ],
  stanceMap: [
    { label: "Pragmatic", x: 78, y: 34, color: "green", note: "Use him to beat Collins" },
    { label: "Skeptical", x: 55, y: 54, color: "yellow", note: "Vote, but do not trust" },
    { label: "Boosters", x: 72, y: 18, color: "blue", note: "Oppo proves he is real" },
    { label: "Hard anti", x: 18, y: 70, color: "pink", note: "Disqualifying empire politics" },
    { label: "Anarchist", x: 10, y: 88, color: "gray", note: "Reject the electoral bargain" },
  ],
  debateMatrix: [
    ["Totenkopf tattoo", "Ignorance; covered fast; obscure symbol", "Knew for years; lied; campaign staff knew"],
    ["Military history", "PTSD redemption; protested then served", "Volunteered to kill; re-enlisted; Blackwater; no reparative accounting"],
    ["Reddit history", "Outgrew 2009-2013; growth chronology", "Racism, homophobia, rape dismissals into 2020s"],
    ["Fetterman", "Different person; no prior political career", "Same staff; same aesthetic; will betray"],
    ["Fight Agency", "They fear him; coincidence with Mamdani", "Manufactured candidate; sheepdog"],
    ["Schumer tie", "Proves establishment feared him", "Proves he is inside the tent"],
    ["Policy vs. character", "Judge M4A, Gaza, wealth tax, town-hall competence", "Judge actions; words are cheap; trust must be earned"],
    ["Fifield / abuse", "GOP operative hit job", "Pattern of behavior across scandals"],
    ["Alternative candidates", "Collins / Mills only viable opponents", "Costello, Smith-Rodriguez, ranked choice unused"],
    ["Hegseth / Trump", "Hypocrisy to focus on Platner ink", "Platner undermines Nazi attacks on the right"],
  ],
  timeline: {
    categories: ["Aug 2025", "Sep 2025", "Oct 2025", "Nov 2025", "Jan 2026", "Apr 2026", "Jun 2026"],
    intensity: [25, 35, 95, 80, 45, 55, 70],
    events: [
      { month: "Aug 2025", label: "Campaign launch", note: "Early anti-imperialist skepticism" },
      { month: "Oct 2025", label: "Tattoo + Reddit peak", note: "Camps crystallize - permanent split" },
      { month: "Apr 2026", label: "Mills dropout", note: "Pragmatic camp vindicated" },
      { month: "Jun 2026", label: "NYT abuse / Fifield", note: "Pragmatic holds; skeptics deepen" },
    ],
  },
  nearConsensus: [
    "Susan Collins is bad - even many anti-Platner voices prefer almost anyone to her",
    "Janet Mills was the wrong Democratic pick - Schumer recruitment seen as malpractice",
    "The Fetterman comparison haunts everything - both sides weaponize it",
    "Stated platform is left of typical Democrats - M4A, anti-AIPAC, Gaza, wealth tax",
    "No organized alternative emerged - Costello, Smith-Rodriguez, ranked-choice coalitions discussed but not built",
    "Biography is the battleground - not whether Maine needs a progressive senator in abstract",
    "Trust is conditional - many sympathetic voices still want discipline, accountability, and real votes",
  ],
  institutionalLayer: [
    ["Bernie Sanders", "Pragmatic legitimacy; skeptics wonder if endorsement erases red flags"],
    ["Working Families Party", "Endorsed; long internal critique of Fetterman-style laundering"],
    ["Schumer / DSCC", "Opposed Mills first; later worked with Platner - both sides cite"],
    ["Jacobin", "Bulk-of-posts defense for pragmatists; ML instances attack as lying"],
    ["AIPAC / pro-Collins PACs", "Funding opposition research - more common hit-job frame than direct intelligence claims"],
    ["Mamdani", "Survivable scandal template for defenders; authenticity benchmark Platner fails for skeptics"],
  ],
};
